name: 'Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    # Use the working directory where the main terraform files are located
    defaults:
      run:
        working-directory: ./infrastructure

    outputs:
      changes: ${{ steps.plan.outputs.changes }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
        
        if [ $exitcode -eq 1 ]; then
          echo "Terraform plan failed!"
          exit 1
        elif [ $exitcode -eq 2 ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload tfplan
      if: steps.plan.outputs.changes == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: infrastructure/tfplan

  apply:
    name: 'Terraform Apply'
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.plan.outputs.changes == 'true'
    runs-on: ubuntu-latest
    environment: production

    # Use the working directory where the main terraform files are located
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Download tfplan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: infrastructure

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
